apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ui.serviceAccountName }}
  labels:
{{ include "coinops-ui.labels" . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ui.imagePullSecretName }}
  labels:
{{ include "coinops-ui.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.ui.imagePullSecretDockerConfigJson | quote }}
