runtimeBackend: postgres
imagePullSecretName: ghcr-pull-secret
imagePullSecretDockerConfigJson: ""
secret:
  name: coinops-app-secrets
  databaseUrl: ""
  rabbitmqUrl: ""
  redisUrl: ""
proxy:
  name: coinops-proxy
  serviceAccountName: coinops-proxy
  image: ""
  servicePort: 8080
  replicas: 1
historyApi:
  name: coinops-history-api
  serviceAccountName: coinops-history-api
  image: ""
  servicePort: 8000
  replicas: 1
consumer:
  name: coinops-history-consumer
  serviceAccountName: coinops-history-consumer
  image: ""
  replicas: 1
