---
k3s_ingress_endpoint_name: app
k3s_ingress_endpoint_namespace: default
k3s_ingress_endpoint_class_name: traefik
k3s_ingress_endpoint_host: ""
k3s_ingress_endpoint_service_name: ""
k3s_ingress_endpoint_service_port: 80
k3s_ingress_endpoint_path: /
k3s_ingress_endpoint_path_type: Prefix
k3s_ingress_endpoint_annotations: {}
k3s_ingress_endpoint_tls_enabled: false
k3s_ingress_endpoint_tls_secret_name: ""
k3s_ingress_endpoint_certificate_name: ""
k3s_ingress_endpoint_cluster_issuer_name: letsencrypt-dns-cloudflare
k3s_ingress_endpoint_wait_for_certificate: true
