---
- name: Run UI validation tasks
  include_tasks: validate.yml
  tags: [ui]

- name: Run UI TLS tasks
  include_tasks: tls.yml
  tags: [ui, tls]

- name: Run UI deployment tasks
  include_tasks: deploy.yml
  tags: [ui]
