---
k3s_local_artifact_dir: "{{ repo_root ~ '/ansible/artifacts' }}"
k3s_local_cluster_kubeconfig_path: "{{ k3s_local_artifact_dir }}/kubeconfig-gcp-k3s-tunneled.yaml"
k3s_remote_kubeconfig_path: /etc/rancher/k3s/k3s.yaml
k3s_remote_fallback_kubeconfig_path: /tmp/coinops-k3s-kubeconfig.yaml
