---
compose_stack_project_dir: ""
compose_stack_compose_template: ""
compose_stack_compose_path: "{{ compose_stack_project_dir }}/compose.yaml"
compose_stack_owner: root
compose_stack_group: root
compose_stack_mode: "0755"
compose_stack_validate_enabled: true
compose_stack_pull_enabled: true
compose_stack_pull_retries: 3
compose_stack_pull_delay: 15
compose_stack_up_enabled: true
compose_stack_up_remove_orphans: true
compose_stack_prune_enabled: true
compose_stack_healthcheck_enabled: false
compose_stack_healthcheck_url: ""
compose_stack_healthcheck_method: GET
compose_stack_healthcheck_status_code: 200
compose_stack_healthcheck_validate_certs: true
compose_stack_healthcheck_retries: 12
compose_stack_healthcheck_delay: 5
