---
k3s_cnpg_enabled: true
k3s_cnpg_namespace: cnpg-system
k3s_cnpg_release_name: cnpg
k3s_cnpg_chart_repo_name: cnpg
k3s_cnpg_chart_repo_url: https://cloudnative-pg.github.io/charts
k3s_cnpg_chart_ref: cnpg/cloudnative-pg
k3s_cnpg_values: {}
