---
- name: Run backend TLS setup tasks
  include_tasks: setup.yml
  tags: [backend_tls, tls]

- name: Run backend TLS certificate tasks
  include_tasks: certificates.yml
  tags: [backend_tls, tls]

- name: Run backend TLS deployment tasks
  include_tasks: deploy.yml
  tags: [backend_tls, tls]
