replicaCount: 2

image: ghcr.io/gethomepage/homepage:latest
imagePullPolicy: IfNotPresent

app:
  name: homepage
  namespace: homepage

serviceAccount:
  create: true
  name: homepage

rbac:
  create: true
  clusterRoleName: homepage

resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

config:
  title: Homepage
  allowedHosts: home.coinops.test
  bookmarks: []
  services: []
  widgets: []

service:
  type: ClusterIP
  port: 3000
