---
cert_manager_namespace: cert-manager
acme_cloudflare_secret_name: cloudflare-api-token-secret
acme_cluster_issuer_name: letsencrypt-dns-cloudflare
acme_directory_url: >-
  {{
    'https://acme-staging-v02.api.letsencrypt.org/directory'
    if certbot_staging else
    'https://acme-v02.api.letsencrypt.org/directory'
  }}
