---
k3s_cert_manager_release_name: cert-manager
k3s_cert_manager_namespace: cert-manager
k3s_cert_manager_chart_ref: oci://quay.io/jetstack/charts/cert-manager
k3s_cert_manager_chart_version: v1.20.2
