{{- range $component := list .Values.proxy .Values.historyApi .Values.consumer }}
{{- if $component.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $component.name }}
  namespace: {{ $component.namespace }}
  labels:
{{ include "coinops-app.labels" $ | indent 4 }}
    app.kubernetes.io/name: {{ $component.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $component.name }}
  minReplicas: {{ $component.autoscaling.minReplicas }}
  maxReplicas: {{ $component.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $component.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
