apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.name }}
  namespace: {{ .Values.proxy.namespace }}
  labels:
{{ include "coinops-app.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.proxy.name }}
  ports:
    - name: http
      port: {{ .Values.proxy.servicePort }}
      targetPort: http
      protocol: TCP

