apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.proxy.serviceAccountName }}
  namespace: {{ .Values.proxy.namespace }}
  labels:
{{ include "coinops-app.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.historyApi.serviceAccountName }}
  namespace: {{ .Values.historyApi.namespace }}
  labels:
{{ include "coinops-app.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.consumer.serviceAccountName }}
  namespace: {{ .Values.consumer.namespace }}
  labels:
{{ include "coinops-app.labels" . | indent 4 }}
