---
helm_install_script_url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
cert_manager_release_name: cert-manager
cert_manager_namespace: cert-manager
cert_manager_chart_ref: oci://quay.io/jetstack/charts/cert-manager
cert_manager_chart_version: v1.20.2
cert_manager_values_file: /tmp/cert-manager-values.yaml
acme_cloudflare_secret_name: cloudflare-api-token-secret
headlamp_tls_enabled: "{{ tls_mode == 'certbot' }}"
headlamp_tls_secret_name: headlamp-tls
headlamp_certificate_name: headlamp-tls
acme_cluster_issuer_name: letsencrypt-dns-cloudflare
acme_directory_url: >-
  {{
    'https://acme-staging-v02.api.letsencrypt.org/directory'
    if certbot_staging else
    'https://acme-v02.api.letsencrypt.org/directory'
  }}
headlamp_release_name: headlamp
headlamp_namespace: kube-system
headlamp_chart_repo_name: headlamp
headlamp_chart_repo_url: https://kubernetes-sigs.github.io/headlamp/
headlamp_chart_ref: headlamp/headlamp
headlamp_values_file: /tmp/headlamp-values.yaml
headlamp_admin_service_account: headlamp-admin
headlamp_admin_cluster_role: cluster-admin
headlamp_local_port: 8080
headlamp_ingress_enabled: "{{ deploy_config.headlamp_ingress_enabled | default(true) | bool }}"
headlamp_ingress_host: "{{ deploy_config.headlamp_hostname | default('headlamp.' ~ app_domain) }}"
headlamp_ingress_class_name: "{{ deploy_config.headlamp_ingress_class_name | default('traefik') }}"
k3s_local_artifact_dir: "{{ repo_root ~ '/ansible/artifacts' }}"
