---
public_ingress_enabled: "{{ deploy_config.public_ingress_enabled | default(true) | bool }}"
public_ingress_release_name: traefik-public
public_ingress_namespace: ingress-public
public_ingress_chart_repo_name: traefik
public_ingress_chart_repo_url: https://traefik.github.io/charts
public_ingress_chart_ref: traefik/traefik
public_ingress_chart_version: ""
public_ingress_class_name: "{{ deploy_config.public_ingress_class_name | default('traefik-public') }}"
public_ingress_http_nodeport: "{{ deploy_config.public_ingress_http_nodeport | default(32080) }}"
public_ingress_https_nodeport: "{{ deploy_config.public_ingress_https_nodeport | default(32443) }}"
